"""Generate the en-US skill model and reviewed action reference. No deployment."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from transport.http.alexa_catalog import ACTIONS, fields, model  # noqa: E402


def main():
    (ROOT / "packaging/alexa/en-US.json").write_text(json.dumps(model(), indent=2) + "\n", encoding="utf-8")
    lines = ["# Alexa action reference", "", "Generated by `python scripts/build_alexa_model.py`. All actions use the linked user's QA workspace during the production freeze.", "",
             "See [the dialogue guide](alexa-action-transport.md) for parameters, confirmations, status and limitations.", "",
             "| MCP action | Say: Alexa, ask job context to… | Transport | Available voice fields / handoff |", "| --- | --- | --- | --- |"]
    for action in ACTIONS.values():
        detail = action.reason if action.mode == "handoff" else ", ".join(fields(action)) or "No fields"
        lines.append(f"| `{action.key}` | {action.phrase} | {action.mode} | {detail} |")
    (ROOT / "docs/alexa-action-reference.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
